### ISSUE TITLE
boostraping

### ISSUE THREAD

**Issue by wbyu** [smirarab/ASTRAL#12]
When I  am doing the bootstraping, however, there was no support value adding to the input tree. The test-file did not work either. I tried to use "-o", then I got the number of "-r"+2 trees. How to get the best species with support values? Thanks.

**Comment by smirarab** [comment]
Read: 

https://github.com/smirarab/ASTRAL#bootstrap-output

**Comment by wbyu** [comment]
What does mean for the  “main” ASTRAL tree? There is no support value for in the input trees.

**Comment by smirarab** [comment]
As the documentation states:

"this [main tree] is the results of running ASTRAL on the best_ml input gene trees. This main tree also includes support values, which are again drawn based on the 100 bootstrap replicate trees."
