### ISSUE TITLE
NullPointerException with multiind:5.0.2 and test_data/song_primates.424.gene.tre

### ISSUE THREAD

**Issue by moskalenko** [smirarab/ASTRAL#15]
java -jar astral.5.0.2.jar -i test_data/song_primates.424.gene.tre

results in a NullPointerException when writing the resulting tree

This is ASTRAL version 5.0.2
Gene trees are treated as unrooted
424 trees read from test_data/song_primates.424.gene.tre
All output trees will be *arbitrarily* rooted at Marmoset
Running the main analysis
Number of taxa: 14 (14 species)
Taxa: [Marmoset, Orangutan, Human, Chimpanzee, Gorilla, Macaque, Galago, Mouse_Lemur, Tree_Shrew, Rat, Tarsier, Rabbit, Horse, Sloth]
Taxon occupancy: {Human=424, Rat=424, Tarsier=424, Galago=424, Rabbit=424, Macaque=424, Sloth=424, Marmoset=424, Tree_Shrew=424, Chimpanzee=424, Mouse_Lemur=424, Horse=424, Orangutan=424, Gorilla=424}
Number of gene trees: 424
0 trees have missing taxa
Calculating quartet distance matrix (for completion of X)
Species tree distances calculated ...
Building set of clusters (X) from gene trees
 
Round 0 of individual  sampling ...
taxon sample [Marmoset, Orangutan, Human, Chimpanzee, Gorilla, Macaque, Galago, Mouse_Lemur, Tree_Shrew, Rat, Tarsier, Rabbit, Horse, Sloth]
Number of clusters after simple addition from gene trees: 339
calculating extra bipartitions to be added at level 1 ...
Number of Clusters after addition by distance: 339
Adding to X using resolutions of greedy consensus ...
Threshold 0.0:
Threshold 0.01:
Threshold 0.02:
Threshold 0.05:
Threshold 0.1:
Threshold 0.2:
Threshold 0.3333333333333333:
polytomy of size 3; rounds with additions with at least 0.01 support: 0; clusters: 339
Number of Clusters after addition by greedy: 339

Number of Default Clusters: 339
partitions formed in 0.274 secs
Dynamic Programming starting after 0.274 secs
Using tree-based weight calculation.
Number of quartet trees in the gene trees: 424424
Size of largest cluster: 14
Total Number of elements weighted: 878
Normalized score (portion of input quartet trees satisfied): 0.9182656965675834
Final optimization score: 389734
Optimal tree inferred in 0.711 secs.
(Gorilla,((Human,Chimpanzee),(Orangutan,(Macaque,(Marmoset,(Tarsier,((Galago,Mouse_Lemur),((Horse,Sloth),(Tree_Shrew,(Rat,Rabbit))))))))));
Quartet score is: 389734
Normalized quartet score is: 0.9182656965675834
.
Exception in thread "main" java.lang.NullPointerException
        at phylonet.coalescent.WQInference.scoreBranches(WQInference.java:415) 
        at phylonet.coalescent.WQInference.scoreSpeciesTreeWithGTLabels(WQInference.java:197)
        at phylonet.coalescent.CommandLine.processSolution(CommandLine.java:636)
        at phylonet.coalescent.CommandLine.runOnOneInput(CommandLine.java:614) 
        at phylonet.coalescent.CommandLine.runInference(CommandLine.java:592)  
        at phylonet.coalescent.CommandLine.main(CommandLine.java:398)

instead of 

Normalized quartet score is: 0.9182656965675834
(Marmoset,((Tarsier,((Galago,Mouse_Lemur)1:2.4018020540034675,((Horse,Sloth)1:2.6056351956741435,(Tree_Shrew,(Rat,Rabbit)1:0.8024369743576611)0.92:0.08540838439417373)1:1.9852014529353605)1:0.655284855661726)1:4.260329699696363,(Macaque,(Orangutan,((Human,Chimpanzee)1:0.6408490436022495,Gorilla)1:2.3251916476229617)1:2.5898315305010144)1:2.7005416959060815)); 
ASTRAL finished in 1.233 secs

with astral-4.10.7

**Comment by smirarab** [comment]
Many thanks for the error report. 5.0.3 fixes the issue.

**Comment by moskalenko** [comment]
Thank you for the rapid fix and release!
