### ISSUE TITLE
Is 5.5.6 the most recent stable version?

### ISSUE THREAD

**Issue by tardigradus** [smirarab/ASTRAL#55]
If later versions can be regarded as stable, could you please consider labeling them?

**Comment by smirarab** [comment]
The latest release is from 5.6.1. Where do you see 5.5.6?

**Comment by smirarab** [comment]
Perhaps 5.6.1 had the wrong name hence the confusion. Anyway, added a release for 5.6.3. Let me know if you do NOT see it. Thanks for the request.
