### ISSUE TITLE
No support values on a specific node when I group specimens into species-groups

### ISSUE THREAD

**Issue by konstakal** [smirarab/ASTRAL#76]
Hello, I am using ASTRAL for my MSc research project, in which we try to untangle the phylogenetic relationships between three amphibian species which are known to habe evolved by a rapid and old radiation. 

When I run ASTRAL without assigning the different specimens into species-groups, I get a support value on said node (see picture 2). However, when I assign the different specimens intos species I don't get this specific node value (see picture 1).

Does anyone know how to fix this? Or if it's possible to use in the "grouped" tree the node value from the "un-grouped" tree? 

Best,
Konstantinos

![out_grouped](https://user-images.githubusercontent.com/73172670/125750484-bf7656d4-a85c-4763-b1e8-ec3f0c9dd2a5.jpg)
![out_ungrouped](https://user-images.githubusercontent.com/73172670/125750490-aa8f3587-efc9-4b1c-975a-e653444b5ae2.jpg)

**Comment by smirarab** [comment]
Konstantinos, this is not the intended behavior. I need to look into it. Before I do so, a question and a request. 

Question: In the case of the first tree, do you manually root the tree? If so, what software do you use to root the tree? Many of the tools for visualization and rooting of the tree have a bug where they mess up support values. 

If the problem is in ASTRAL's output, not the rooting software, it would be helpful for me to have your input files to be able to reproduce the problem; perhaps you could email them to me (smirarab@ucsd.edu).

**Comment by konstakal** [comment]
I use FigTree to mid-point-root the tree. I think the issue is in the ASTRAL output, because I can only see one support value (the one also shown in FigTree). I will send you the input and output asap.

Thanks

**Comment by smirarab** [comment]
Konstantinos, this is clearly a rooting thing. Your tree has only 4 species. An unrooted tree with 4 species has only 1 branch (just draw a quartet tree to see this). So there must be just one support branch and there is one support branch. When you manually root at species 1, you create an artificial branch, which is completely based on your knowledge of the correct root, not what ASTRAL outputs. 

This is no different than a tree inferred from RAxML or any other tool. A tree with 4 species has only one branch (i.e., non-trivial bipartition) and therefore has only one branch support value.

**Comment by konstakal** [comment]
Dear Siavash,

Thank you very much for your reply. Indeed you are right, this has to do
with the number of taxa used.

The weird thing with my project (we are dealing with an old and rapid
speciation of 3 taxa) is that RAxML and ASTRAL (with outgroup) suggest
topology A, while SNAPP (1 million generation, ESS values over 500)
suggests topology B. If I use ASTRAL (without outgroup) without assigning
the different individuals into species-groups (which is probably wrong) I
get topology B, which is also strange. All the aforementioned results have
nodes with absolute support values (100% bootstraps/1 posterior
probabilities). Do you perhaps have any insight on how to interpret this?
Since both SNAPP and ASTRAL are based on the MSC model, shouldn't they
suggest the same resolution?

Best,
Konstantinos

**Comment by smirarab** [comment]
SNAPP uses a different model of sequence evolution than what you are likely using to get the gene trees; SNAPP is bi-allelic. For ASTRAL analyses, if your gene trees have low support branches, try contracting those low support branches.

**Comment by konstakal** [comment]
Hello again,

That's the weird thing. I do not get low support in ASTRAL. I get very high
nodes.

Nevertheless, I have another question that I was hoping you could help me
with. When I run 3-taxa ASTRAL (i.e. without the outgroup), even though I
do not get any support values I get this conflicting suggestions between
the "optimal" and the final tree I get in the output (as you can see in the
results of ASTRAL):

Number of gene trees: 6649

Optimization score: 1651613

Optimal tree inferred in 66.168 secs.

(nesterovi,(vittatus,ophryticus));

Final quartet score is: 4924993
Final normalized quartet score is: 0.7054398441584485

Extended species tree:

((VITIS1,VIT619,VIT610,VIT654,VIT612)1:0.7178775382235492,((OPH690,OPH491,OPH676,OPH377,OPH299)1:0.6387358950200033,(NES206,NES007,NES172,NES031,NES581)1:0.6853777417197996))


In this case optimal tree: (nesterovi,(vittatus,ophryticus))

Tree in the final output: (vittatus,(nesterovi,ophryticus))


How can we explain this? Why is there a difference between the two trees?
Which one should I trust? Is it even possible to do a 3-taxa-analysis on
ASTRAL since there are no support values?


Best,

Konstantinos

**Comment by smirarab** [comment]
Konstantinos, a three taxon **unrooted** tree is meaningless. I am sure you know that ASTARL outputs unrooted trees. All unrooted three-taxon trees are the same. I should make the change so that with three taxon, multile-individual ASTRAL does not run.
