### ISSUE TITLE
Error: Unable to initialize main class phylonet.coalescent.CommandLine

### ISSUE THREAD

**Issue by sunnyEV** [smirarab/ASTRAL#84]
**Describe the bug**
Its a java error 
Error: Unable to initialize main class phylonet.coalescent.CommandLine
Caused by: java.lang.NoClassDefFoundError: com/martiansoftware/jsap/StringParser

**To Reproduce**
`java -Xmx60g -jar astral.5.7.1.jar -i mlbest.trees -b mlboot.txt -o species_boot.trees > species_boot.trees.log `

**Log file**
Error: Unable to initialize main class phylonet.coalescent.CommandLine
Caused by: java.lang.NoClassDefFoundError: com/martiansoftware/jsap/StringParser

** Version** 
5.7.1

**Additional context**

**Comment by swa-mi** [comment]
I was facing the same problem. It seems like ASTRAL is looking for `lib/JSAP-2.1.jar` but I had moved the `astral.5.7.1.jar` file away and I was running it directly. Running the `astral.5.7.1.jar` file when it is inside the ASTRAL directory solved the issue.

**Comment by sunnyEV** [comment]
Thanks mate.

**Comment by edyane0209** [comment]
I am trying to run the Astral software, but when I do it, a message appears: Error: "Unable to access jarfile astral.jar". Just try to run the command "java -jar astral.5.7.8.jar" inside the directory where it is installed, but no success. Can someone help?

**Comment by smirarab** [comment]
@edyane0209 find where the file is located and run it from there. If it doesn't work, please open a new issue with more details and I will have a look.
