### ISSUE TITLE
test_data/simulated_14taxon.default.tre missing

### ISSUE THREAD

**Issue by imaa9** [smirarab/ASTRAL#89]
It seems this example file is missing when cloning the git directory

Here are the contents of the Astral/test_data directory when I unzip it:

bs-files
song_mammals.424genes.bs-trees.zip
astral-1KP-genetrees.tre
newtree.tre
simulated_primates_5X.10.gene.tre
simulated_primates_5X.10.bootstrap.gene.tre
2021 simulated_14taxon.gene.tre
2021 README
2021 namemap-1kp.txt
1KP-genetrees.tre
1KP-genetrees-BS10.tre
100-simulated-boot
song_primates.424.gene.tre
song_mammals.424.gene.tre
1KP-genetrees-completed.tre.completed_gene_trees
1KP-genetrees-completed.tre
head-1KP-genetrees-completed.tre.completed_gene_trees
head-1KP-genetrees.tre
song_mammals.tre
1kp.tre
1kp.log

The example command appears to call a file that is not present:
java -jar astral.5.7.8.jar -q test_data/simulated_14taxon.default.tre -i test_data/simulated_14taxon.gene.tre -o test_data/simulated_scored.tre 2> test_data/simulated_scored.log

Hopefully I haven't missed something here!

**Comment by smirarab** [comment]
The file is there. I just downloaded the zip file and checked. 

For whatever reason, it seems in your directory there is a 2021 put in front of the name? 

2021 simulated_14taxon.gene.tre

**Comment by imaa9** [comment]
Hi Siavash,

Sorry, that was a typo on my part. However, that file doesn't have
"default" in it, as the command calls for. Did I misunderstand something
here?


*Inbar Maayan*
PhD Candidate | *she/her*
Department of Organismic and Evolutionary Biology
Harvard University
***@***.***
www.inbarmaayan.com

**Comment by smirarab** [comment]
Sorry for that mistake and sorry for missing this issue until now. That file was supposed to be built in previous steps, but I had moved around steps and it didn't exist at this point. I updated the tutorial in 068a4b2497f61c866c4727bfbfd78b4361ba27c8.
