### ISSUE TITLE
Regarding combining individual gene trees into one file

### ISSUE THREAD

**Issue by Upendra19993** [smirarab/ASTRAL#90]
Hi, 

When we run ASTRAL, we have to generate individual gene trees and need to use all these gene trees as one input file. I  am using 47 genes and therefore have 47 gene trees. I want to know how to get all 47 gene trees into one file. I didn't find a way to get all these trees into one file.

**Comment by biocyberman** [comment]
A `cat` command in Linux would work perfectly. For example: `cat file1.tre file2.tre ... file47.tre > all_trees.tre`.

**Comment by smirarab** [comment]
Yes, `cat` is perfectly fine for MacOS and Linux. If you use windows, I am sure there are ways to combine planin text files, but I am not sure what. You can google it.
